### ISSUE TITLE
concrete-ml won't import

### ISSUE THREAD

**Issue by HamidFsian** [zama-ai/concrete-ml#1]
Hello,
I have installed concrete-ml using pip and followed the steps to install pygraphiz (pygraphiz is working).

**_ERROR: Could not find a version that satisfies the requirement concrete-compiler<0.5.0,>=0.4.0 (from concrete-numpy[full]<0.4.0,>=0.3.0->concrete-ml) (from versions: none)
ERROR: No matching distribution found for concrete-compiler<0.5.0,>=0.4.0 (from concrete-numpy[full]<0.4.0,>=0.3.0->concrete-ml)
_**

I am using  : 
     ubuntu 20.04.4
     python 3.8.10

**Comment by andrei-stoian-zama** [comment]
Hi,

It could be related to a setuptools package in you python environment that is not up to data. Could you try 

```
pip install -U pip wheel setuptools
```

and then try again the installation of concrete-ml ?

**Comment by bcm-at-zama** [comment]
Is it fixed now for you, @HamidFsian ? From your message in https://discord.com/channels/901152454077452399/908644240148541450/960831975785111564, it looks like it has been fixed by upgrading ubuntu. 

If this is fixed, let's close. Else, please come back to us, thanks

**Comment by HamidFsian** [comment]
Thank you it worked ! :D

**Comment by lidh15** [comment]
The same problem. 
Upgrade pip wheel setuptools didn't work. 
Download concrete-compiler.whl and unzip the wheel file into python3.8/site-packages/ finally worked.
Btw I'm really curious about why concrete requires graphvis, there is no visualization at least in the demo.

**Comment by bcm-at-zama** [comment]
From https://github.com/zama-ai/concrete-ml/issues/1#issuecomment-1090256662, it appears that one also had to upgrade ubuntu.

**Comment by bcm-at-zama** [comment]
Concrete-Numpy uses graphviz for drawing graphs, see https://docs.zama.ai/concrete-numpy/stable/user/howto/printing_and_drawing.html. Examples of such graphs: https://docs.zama.ai/concrete-numpy/stable/dev/explanation/float-fusing.html
