### ISSUE TITLE
concrete-ml installation issue

### ISSUE THREAD

**Issue by sjain70** [zama-ai/concrete-ml#11]
I am unable to resolve following error while installing:
ERROR: Could not find a version that satisfies the requirement concrete-compiler<0.5.0,>=0.4.0 (from concrete-numpy[full]) (from versions: none)
ERROR: No matching distribution found for concrete-compiler<0.5.0,>=0.4.0

=============
I followed following 2 steps:
1) docker pull zamafhe/concrete-ml:latest
2) pip install concrete-ml>s1.txt

s1.txt has been attached
[s1.txt](https://github.com/zama-ai/concrete-ml/files/8799200/s1.txt)

**Comment by bcm-at-zama** [comment]
Hello @sjain70,  

It is either Docker or pip install.

If you are trying to use Docker, you don't need to install concrete-ml, it is already there. You do `docker run --rm -it zamafhe/concrete-ml:latest /bin/bash` then eg `python3` and `import concrete.ml`.

If you prefer pip, you may need to upgrade by `pip install --upgrade pip`. 

If it doesn't solve the problem, could you tell us on which OS you're, please?

**Comment by bcm-at-zama** [comment]
No answer for 2 weeks, I hope it is fixed. Don't hesitate to ping us back if still a problem

**Comment by ballesterosbr** [comment]
Had the same problem using pip. Concrete-ml does not support python 3.10 (Concrete-ml requires Python >=3.8, <3.10 from [Pypi concrete-ml 0.2.1](https://pypi.org/project/concrete-ml/0.2.1/)).
