### ISSUE TITLE
is independent of the actual bit precision limitation?

### ISSUE THREAD

**Issue by maxwellgodv** [zama-ai/concrete-ml#114]
<img width="868" alt="1690808205095" src="https://github.com/zama-ai/concrete-ml/assets/127387074/389a6ad0-10de-473e-960d-5f8ba5f74cb5">
is independent of the actual bit precision limitation.
May I know how to understand this sentence？What is actual bit precision limitation?

**Comment by andrei-stoian-zama** [comment]
> <img alt="1690808205095" width="868" src="https://user-images.githubusercontent.com/127387074/257226249-389a6ad0-10de-473e-960d-5f8ba5f74cb5.png"> is independent of the actual bit precision limitation. May I know how to understand this sentence？What is actual bit precision limitation?

Since Concrete Python 2.0 the simulation itself requires that the circuit respect the bit-width constraint. This constraint is: all inputs and intermediary values in the function to be compiled must be <=16bit if and only if lookup tables are used or univariate functions. If there are no lookup tables or univariate functions, you can exceed 16b with an upper bound determined by the operation that you perform. 

If you want to measure maximum bitwidth that the circuit would attain you can use "tracing" like this:

```
import numpy as np
from concrete import fhe

configuration = fhe.Configuration(
    enable_unsafe_features=True,
    use_insecure_key_cache=True,
    insecure_key_cache_location=".keys",
    single_precision=False,
    parameter_selection_strategy=fhe.ParameterSelectionStrategy.MULTI,
)

@fhe.compiler({"x": "encrypted", "y": "encrypted"})
def f(x, y):
    return x + y

inputset = [
    (
        np.random.randint(0, 10, size=()),
        np.random.randint(0, 10, size=()),
    )
    for _ in range(100)
]
circuit = f.trace(inputset, configuration)

print(circuit.maximum_integer_bit_width())
```

**Comment by RomanBredehoft** [comment]
Just a quick note what @andrei-stoian-zama said above : the current Concrete-ML public version does not use Concrete Python 2.0 yet, but it will soon ! So currently, you might expect different constraints. For example, simulating circuits with 16 bits is possible, which is what `is independent of the actual bit precision limitation` was referring to. However, this won't be the case in the near future, so I would recommend you not to take this as granted 😉

**Comment by maxwellgodv** [comment]
<img width="952" alt="1690888094402" src="https://github.com/zama-ai/concrete-ml/assets/127387074/1a6a0835-0beb-42f9-af88-4df8e445d650">
Can I  measure maximum bitwidth like this？
What are the current constraints？
