### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by srinu1093** [zama-ai/concrete-ml#14]
Is it possible to install concrete-ml through Jupyter Notebook using the pip command on a Windows machine?

**Comment by jfrery** [comment]
Hello! Currently we do not support windows as the core library that handles the fully homomorphic encryption [does not support windows](https://github.com/zama-ai/concrete#windows).

You have a few options:
- use docker for windows with port forwarding such as to have jupyter in your windows web browser.
- or simply use [WSL](https://docs.microsoft.com/en-us/windows/wsl/install)

Let us know if that works for you.

**Comment by srinu1093** [comment]
Yes, it is working fine! Thanks!!
