### ISSUE TITLE
What is the difference between a graph and a circuit

### ISSUE THREAD

**Issue by maxwellgodv** [zama-ai/concrete-ml#147]
Hello，What is the difference between a graph and a circuit？

**Comment by umut-sahin** [comment]
[Graph](https://github.com/zama-ai/concrete/blob/main/frontends/concrete-python/concrete/fhe/representation/graph.py#L21) is for representing computation (e.g., a graph can represent `(x * 2) + y`).
[Circuit](https://github.com/zama-ai/concrete/blob/main/frontends/concrete-python/concrete/fhe/compilation/circuit.py#L30) is the result of compilation.

We convert Python functions to graphs, and then graphs to [MLIR](https://mlir.llvm.org/). We give the MLIR to our compiler, compiler compiles the code into a native binary, and gives back a circuit that contains that native binary. And we use circuits for encryption, running, etc.

**Comment by maxwellgodv** [comment]
Thanks，I have one more question，How is graph evaluation and noise simulation implemented in `fhe_simulation_inference `function？

**Comment by RomanBredehoft** [comment]
Hello @maxwellgodv and sorry for the late answer, most of our team was off for the past days ! You can find more information about the simulation process in [Concrete's documentation](https://docs.zama.ai/concrete/tutorials/simulation). However, Concrete-ML does not use Concrete's latest simulation version yet (it will soon). This means that currently, simulation is basically still walking through the graph and adding random noise when needed. Here's a [similar answer](https://github.com/zama-ai/concrete-ml/issues/95#issuecomment-1639824036) from @umut-sahin. 

Hope this helps !

**Comment by RomanBredehoft** [comment]
Hello @maxwellgodv, if you think we successfully answered your question, feel free to close this issue !
