### ISSUE TITLE
the security level

### ISSUE THREAD

**Issue by Ritian-Li** [zama-ai/concrete-ml#19]
Hi, I saw a parameter (n_bits=3) when defining a model. Does it mean the security level? Or when I use it to encrypt inference, does it satisfy 128-bits security?

**Comment by fd0r** [comment]
Hello @Ritian-Li ,
Thank you for your interest in Concrete-ML !
Could you please ask your question on the community website https://community.zama.ai/c/concrete-ml/ ?
It's easier for us to manage. 🙂

**Comment by fd0r** [comment]
Hello @Ritian-Li,
Since this was answered on https://community.zama.ai/t/the-security-level/252/2 , is it okay with you if we close the issue?
