### ISSUE TITLE
Not installing with pip (python 3.10 not supported workaround?)

### ISSUE THREAD

**Issue by ballesterosbr** [zama-ai/concrete-ml#27]
NOTE: This is not actually a bug.

## Summary

What happened/what you expected to happen?

Not abe to install `concrete-ml` with pip. Requires Python >=3.8, <3.10 from [Pypi concrete-ml 0.2.1](https://pypi.org/project/concrete-ml/0.2.1/).

EDIT: Sorry I printed the pip list from different python (3.9) version.

I do not have `concrete-numpy` installed.

## Description

- versions affected: 0.1.0; 0.1.1; 0.2.0; 0.2.1.
- python version: Python 3.10.4
- pip version: 22.2.2
- config (optional: HW, OS): Ubuntu 20.04.1 LTS
- workaround (optional): if you’ve a way to workaround the issue
- proposed fix (optional): if you’ve a way to fix the issue

Step by step procedure someone should follow to trigger the bug:

```
$ pip install concrete-ml
ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python >=3.8,<3.10; 0.1.1 Requires-Python >=3.8,<3.10; 0.2.0 Requires-Python >=3.8,<3.10; 0.2.1 Requires-Python >=3.8,<3.10
ERROR: Could not find a version that satisfies the requirement concrete-ml (from versions: none)
ERROR: No matching distribution found for concrete-ml
```

**Comment by bcm-at-zama** [comment]
Hello @ballesterosbr . We currently don't support officially 3.10 (nor 3.7, for people on Google Collab or Kaggle) but we'll add it soon. 

In the meantime, would you like to:
- either, run your tests on python 3.9 (the safest, since we test it like that)
- or, try installing as `pip3 install --ignore-requires-python  concrete-ml`
?

Tell us how it goes. Cheers

**Comment by ballesterosbr** [comment]
Hello @bcm-at-zama, both work perfectly! Forgot to mention that I'm using jupyter notebooks, but I can run my scripts on console in the meantime.
