### ISSUE TITLE
The 'zama-ai/concrete-ml' repository doesn't contain the 'docs/_apidoc/concrete.ml.sklearn.html' path in 'release/0.3.x'

### ISSUE THREAD

**Issue by vridhi-vk** [zama-ai/concrete-ml#28]
## Summary

I'm unable to view the documentation of the concrete ml models. I wanted to try and use logistic regression on India pima diabetes dataset.

On trying to read the docs from <a href="https://docs.zama.ai/concrete-ml/built-in-models/linear">here </a>, I get the error: 
<p>The 'zama-ai/concrete-ml' repository doesn't contain the 'docs/_apidoc/concrete.ml.sklearn.html' path in 'release/0.3.x'.</p>

**Comment by bcm-at-zama** [comment]
Hello, 

Sorry for that and thanks for reporting. 

Indeed, for 0.3, our API documentation over GitBook was not perfect and we plan to update it. 

- regarding the doc: the best is currently to download https://github.com/zama-ai/concrete-ml/blob/release/0.3.x/docs/autogenerated/pdoc.pdf : at page 75, you'll find "
Module src.concrete.ml.sklearn" 

- you also have examples for logistic regression, which would be the starting point, in my opinion: https://github.com/zama-ai/concrete-ml/blob/release/0.3.x/docs/advanced_examples/LogisticRegression.ipynb

- where you able to do your logistic regression? If not, you can get some help in https://community.zama.ai/c/concrete-ml/8

In next release, we should have a better management of API docs in GitBook.
Cheers

**Comment by vridhi-vk** [comment]
okay, thank you!
