### ISSUE TITLE
New Feature - Biclustering with CML

### ISSUE THREAD

**Issue by ShokofehVS** [zama-ai/concrete-ml#30]
Hello. 

Thank you for your great work!
I have a project to apply FHE on gene expression data for instance two of them 

1. [Yeast expression matrix](https://arep.med.harvard.edu/biclustering/yeast.matrix), based on [Tavazoie et al.](http://arep.med.harvard.edu/network_discovery/) 8224 rows and 17 columns, 4 bytes for each element, with -1 indicating a missing value.
2. [Human expression matrix](https://arep.med.harvard.edu/biclustering/lymphoma.matrix), based on [Alizadeh et al.](http://llmpp.nih.gov/lymphoma) with 4026 rows and 96 columns, 4 bytes for each element, and 999 indicating a missing value.

and analyze encrypted input data with Biclustering algorithms like  
[Cheng and Church Algorithm ](https://www.researchgate.net/publication/12345321_Biclustering_of_Expression_Data). 

**Biclustering can be performed with the module `sklearn.cluster.bicluster` ; more information can be found [here](https://scikit-learn.org/stable/modules/biclustering.html). 
**There are also wide range of Python libraries of biclustering algorithms like [biclustlib](https://github.com/padilha/biclustlib). 

I am very excited to contribute with Zama community to make this unsupervised machine learning algorithm run on concrete-ml and make gene expression data encrypted during process. I would be happy to provide more detailed information if needed.

Many thanks 
Shokofeh

**Comment by bcm-at-zama** [comment]
Thanks @ShokofehVS , we keep your issue for further quarters. Hopefully, when 16b is managed on Concrete-ML side (it is already done in Concrete and will soon be in Concrete-Numpy), it should be easier.

**Comment by ShokofehVS** [comment]
Perfect! looking forward to hearing from you.

**Comment by bcm-at-zama** [comment]
Hello @ShokofehVS . So, as I told you, we have created an internal issue for this request. I am going to close this one, and we'll reopen / let you know when we work on it. Thanks once again for your interest in Concrete-ML and your ideas. Cheers

**Comment by ShokofehVS** [comment]
Hi @bcm-at-zama, I hope you're doing well. No problem! Thank you and your team for making such a creative ecosystem. Keep up the good work.
