### ISSUE TITLE
Does this library support running on GPU?

### ISSUE THREAD

**Issue by wzjin2017** [zama-ai/concrete-ml#390]
Thanks for the awesome work! I was wondering if there is any way to run the library on GPUs?

**Comment by fd0r** [comment]
Hello @wzjin2017 ,

Concrete doesn't have GPU support yet, but it is a work in progress!

**Comment by Jerry0810** [comment]
Hello @fd0r ,

I noticed that Concrete supports CUDA, there has two folder which named concrete-cpu and concrete-gpu. So I'm curious why Concrete-ML doesn't support.

**Comment by fd0r** [comment]
Hello @Jerry0810 , GPU integration is still in the works and the integration will have to be done in the python frontend.

The team is working hard to get it to you as soon as possible 🙂

**Comment by summer-xrx** [comment]
Hello @fd0r ，
I was wondering if there is any way to run the library on GPUs?

**Comment by Doaa-mathema** [comment]
Hello,
I wanted to ask if there any update about supporting the gpu/cuda computation in the inference phase
Thanks

**Comment by kcelia** [comment]
Hi, 
Coming soon !
For now, GPU support is available in Concrete. We are currently working on integrating it with Concrete ML.
We will update this issue, once this is completed.

**Comment by Doaa-mathema** [comment]
@kcelia Thank you so much for the fast reply

**Comment by SandPhoenixX517** [comment]
Hello guys,
any update on this? Is it going to be there by the end of September?

**Comment by bcm-at-zama** [comment]
Hello, Concrete ML with a GPU support should be available by the end of the quarter, which is early october yes

**Comment by kcelia** [comment]
Hi @SandPhoenixX517, @Doaa-mathema, @wzjin2017, @summer-xrx, 

The GPU support has been released in Concrete ML !! So, closing this issue.

Let us know if you have any questions in our (discord)[https://discord.com/channels/901152454077452399/1083021638544670720] channel.
