### ISSUE TITLE
encrypted_sentiment_analysis version conflict

### ISSUE THREAD

**Issue by I-E-E-E** [zama-ai/concrete-ml#40]
# concrete v:4.0.0 conflicts with python3.9

ERROR: Ignored the following versions that require a different python version: 4.0.0 Requires-Python >=3.6,<3.9; 4.0.1 Requires-Python >=3.6,<3.9; 4.1.0 Requires-Python >=3.6,<3.9
ERROR: Could not find a version that satisfies the requirement concrete-compiler<0.20.0,>=0.19.0 (from concrete-numpy) (from versions: 0.1.1, 0.1.2, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.9.0, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.15.0, 0.16.0)
ERROR: No matching distribution found for concrete-compiler<0.20.0,>=0.19.0

**Comment by bcm-at-zama** [comment]
Hello,

- what is you OS please
- did you follow instructions in https://docs.zama.ai/concrete-ml/getting-started/pip_installing#installation, ie 

```

pip install -U pip wheel setuptools
pip install concrete-ml
```

Cheers

**Comment by bcm-at-zama** [comment]
And there is I think no reason to try Concrete-ML 0.4.0, you should move to the most recent one, ie 0.5.1

**Comment by bcm-at-zama** [comment]
Anyway, was able to install 0.4.0 on my macOS (intel) just now:

<details>
pip install concrete-ml==0.4.0
Looking in indexes: https://pypi.org/simple, https://repo.zama.ai/repository/internal-pypi/simple
Collecting concrete-ml==0.4.0
  Using cached concrete_ml-0.4.0-py3-none-any.whl (97 kB)
Requirement already satisfied: onnx<2.0.0,>=1.11.0 in ./.venv/lib/python3.9/site-packages (from concrete-ml==0.4.0) (1.12.0)
Collecting scikit-learn<2.0.0,>=1.1.0
  Using cached scikit_learn-1.1.3-cp39-cp39-macosx_10_9_x86_64.whl (8.7 MB)
Collecting numpy<2.0.0,>=1.22.3
  Using cached numpy-1.23.4-cp39-cp39-macosx_10_9_x86_64.whl (18.1 MB)
Requirement already satisfied: concrete-ml-extensions-brevitas==0.0.0 in ./.venv/lib/python3.9/site-packages (from concrete-ml==0.4.0) (0.0.0)
Requirement already satisfied: onnxoptimizer<0.3.0,>=0.2.7 in ./.venv/lib/python3.9/site-packages (from concrete-ml==0.4.0) (0.2.7)
Requirement already satisfied: xgboost<2.0.0,>=1.5.2 in ./.venv/lib/python3.9/site-packages (from concrete-ml==0.4.0) (1.6.2)
Requirement already satisfied: skorch<0.12.0,>=0.11.0 in ./.venv/lib/python3.9/site-packages (from concrete-ml==0.4.0) (0.11.0)
Requirement already satisfied: setuptools in ./.venv/lib/python3.9/site-packages (from concrete-ml==0.4.0) (65.5.0)
Collecting scipy<2.0.0,>=1.8.0
  Using cached scipy-1.9.3-cp39-cp39-macosx_10_9_x86_64.whl (34.3 MB)
Requirement already satisfied: torch<2.0.0,>=1.11.0 in ./.venv/lib/python3.9/site-packages (from concrete-ml==0.4.0) (1.12.1)
Collecting concrete-numpy==0.8.0
  Using cached concrete_numpy-0.8.0-py3-none-any.whl (68 kB)
Requirement already satisfied: protobuf==3.19.4 in ./.venv/lib/python3.9/site-packages (from concrete-ml==0.4.0) (3.19.4)
Requirement already satisfied: hummingbird-ml[onnx]<0.5.0,>=0.4.4 in ./.venv/lib/python3.9/site-packages (from concrete-ml==0.4.0) (0.4.4)
Requirement already satisfied: typing-extensions>=3.7.4 in ./.venv/lib/python3.9/site-packages (from concrete-ml-extensions-brevitas==0.0.0->concrete-ml==0.4.0) (4.4.0)
Requirement already satisfied: dependencies==2.0.1 in ./.venv/lib/python3.9/site-packages (from concrete-ml-extensions-brevitas==0.0.0->concrete-ml==0.4.0) (2.0.1)
Requirement already satisfied: future-annotations in ./.venv/lib/python3.9/site-packages (from concrete-ml-extensions-brevitas==0.0.0->concrete-ml==0.4.0) (1.0.0)
Requirement already satisfied: packaging in ./.venv/lib/python3.9/site-packages (from concrete-ml-extensions-brevitas==0.0.0->concrete-ml==0.4.0) (21.3)
Requirement already satisfied: matplotlib<4.0.0,>=3.5.1 in ./.venv/lib/python3.9/site-packages (from concrete-numpy==0.8.0->concrete-ml==0.4.0) (3.5.3)
Collecting concrete-compiler<0.20.0,>=0.19.0
  Using cached https://repo.zama.ai/repository/internal-pypi/packages/concrete-compiler/0.19.0/concrete_compiler-0.19.0-cp39-cp39-macosx_11_0_x86_64.whl (46.1 MB)
Requirement already satisfied: networkx<3.0.0,>=2.6.3 in ./.venv/lib/python3.9/site-packages (from concrete-numpy==0.8.0->concrete-ml==0.4.0) (2.6.3)
Requirement already satisfied: Pillow<10.0.0,>=9.0.0 in ./.venv/lib/python3.9/site-packages (from concrete-numpy==0.8.0->concrete-ml==0.4.0) (9.2.0)
Requirement already satisfied: onnxconverter-common>=1.6.0 in ./.venv/lib/python3.9/site-packages (from hummingbird-ml[onnx]<0.5.0,>=0.4.4->concrete-ml==0.4.0) (1.12.2)
Requirement already satisfied: dill in ./.venv/lib/python3.9/site-packages (from hummingbird-ml[onnx]<0.5.0,>=0.4.4->concrete-ml==0.4.0) (0.3.6)
Requirement already satisfied: psutil in ./.venv/lib/python3.9/site-packages (from hummingbird-ml[onnx]<0.5.0,>=0.4.4->concrete-ml==0.4.0) (5.9.3)
Requirement already satisfied: onnxruntime>=1.0.0 in ./.venv/lib/python3.9/site-packages (from hummingbird-ml[onnx]<0.5.0,>=0.4.4->concrete-ml==0.4.0) (1.13.1)
Requirement already satisfied: skl2onnx>=1.7.0 in ./.venv/lib/python3.9/site-packages (from hummingbird-ml[onnx]<0.5.0,>=0.4.4->concrete-ml==0.4.0) (1.12)
Requirement already satisfied: onnxmltools>=1.6.0 in ./.venv/lib/python3.9/site-packages (from hummingbird-ml[onnx]<0.5.0,>=0.4.4->concrete-ml==0.4.0) (1.11.1)
Requirement already satisfied: joblib>=1.0.0 in ./.venv/lib/python3.9/site-packages (from scikit-learn<2.0.0,>=1.1.0->concrete-ml==0.4.0) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./.venv/lib/python3.9/site-packages (from scikit-learn<2.0.0,>=1.1.0->concrete-ml==0.4.0) (3.1.0)
Requirement already satisfied: tqdm>=4.14.0 in ./.venv/lib/python3.9/site-packages (from skorch<0.12.0,>=0.11.0->concrete-ml==0.4.0) (4.64.1)
Requirement already satisfied: tabulate>=0.7.7 in ./.venv/lib/python3.9/site-packages (from skorch<0.12.0,>=0.11.0->concrete-ml==0.4.0) (0.8.10)
Requirement already satisfied: PyYAML in ./.venv/lib/python3.9/site-packages (from concrete-compiler<0.20.0,>=0.19.0->concrete-numpy==0.8.0->concrete-ml==0.4.0) (6.0)
Requirement already satisfied: kiwisolver>=1.0.1 in ./.venv/lib/python3.9/site-packages (from matplotlib<4.0.0,>=3.5.1->concrete-numpy==0.8.0->concrete-ml==0.4.0) (1.4.4)
Requirement already satisfied: fonttools>=4.22.0 in ./.venv/lib/python3.9/site-packages (from matplotlib<4.0.0,>=3.5.1->concrete-numpy==0.8.0->concrete-ml==0.4.0) (4.38.0)
Requirement already satisfied: cycler>=0.10 in ./.venv/lib/python3.9/site-packages (from matplotlib<4.0.0,>=3.5.1->concrete-numpy==0.8.0->concrete-ml==0.4.0) (0.11.0)
Requirement already satisfied: python-dateutil>=2.7 in ./.venv/lib/python3.9/site-packages (from matplotlib<4.0.0,>=3.5.1->concrete-numpy==0.8.0->concrete-ml==0.4.0) (2.8.2)
Requirement already satisfied: pyparsing>=2.2.1 in ./.venv/lib/python3.9/site-packages (from matplotlib<4.0.0,>=3.5.1->concrete-numpy==0.8.0->concrete-ml==0.4.0) (3.0.9)
Requirement already satisfied: coloredlogs in ./.venv/lib/python3.9/site-packages (from onnxruntime>=1.0.0->hummingbird-ml[onnx]<0.5.0,>=0.4.4->concrete-ml==0.4.0) (15.0.1)
Requirement already satisfied: sympy in ./.venv/lib/python3.9/site-packages (from onnxruntime>=1.0.0->hummingbird-ml[onnx]<0.5.0,>=0.4.4->concrete-ml==0.4.0) (1.10.1)
Requirement already satisfied: flatbuffers in ./.venv/lib/python3.9/site-packages (from onnxruntime>=1.0.0->hummingbird-ml[onnx]<0.5.0,>=0.4.4->concrete-ml==0.4.0) (1.12)
Requirement already satisfied: tokenize-rt>=3 in ./.venv/lib/python3.9/site-packages (from future-annotations->concrete-ml-extensions-brevitas==0.0.0->concrete-ml==0.4.0) (5.0.0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib<4.0.0,>=3.5.1->concrete-numpy==0.8.0->concrete-ml==0.4.0) (1.16.0)
Requirement already satisfied: humanfriendly>=9.1 in ./.venv/lib/python3.9/site-packages (from coloredlogs->onnxruntime>=1.0.0->hummingbird-ml[onnx]<0.5.0,>=0.4.4->concrete-ml==0.4.0) (10.0)
Requirement already satisfied: mpmath>=0.19 in ./.venv/lib/python3.9/site-packages (from sympy->onnxruntime>=1.0.0->hummingbird-ml[onnx]<0.5.0,>=0.4.4->concrete-ml==0.4.0) (1.2.1)
Installing collected packages: numpy, scipy, concrete-compiler, scikit-learn, concrete-numpy, concrete-ml
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.6
    Uninstalling numpy-1.21.6:
      Successfully uninstalled numpy-1.21.6
  Attempting uninstall: scipy
    Found existing installation: scipy 1.7.3
    Uninstalling scipy-1.7.3:
      Successfully uninstalled scipy-1.7.3
  Attempting uninstall: concrete-compiler
    Found existing installation: concrete-compiler 0.21.0
    Uninstalling concrete-compiler-0.21.0:
      Successfully uninstalled concrete-compiler-0.21.0
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.0.2
    Uninstalling scikit-learn-1.0.2:
      Successfully uninstalled scikit-learn-1.0.2
  Attempting uninstall: concrete-numpy
    Found existing installation: concrete-numpy 0.9.0rc2
    Uninstalling concrete-numpy-0.9.0rc2:
      Successfully uninstalled concrete-numpy-0.9.0rc2
  Attempting uninstall: concrete-ml
    Found existing installation: concrete-ml 0.6.0
    Uninstalling concrete-ml-0.6.0:
      Successfully uninstalled concrete-ml-0.6.0
Successfully installed concrete-compiler-0.19.0 concrete-ml-0.4.0 concrete-numpy-0.8.0 numpy-1.23.4 scikit-learn-1.1.3 scipy-1.9.3
</details>

**Comment by I-E-E-E** [comment]
> And there is I think no reason to try Concrete-ML 0.4.0, you should move to the most recent one, ie 0.5.1

I followed this tutorial⬇️
https://github.com/zama-ai/concrete-ml/tree/release/0.5.x/use_case_examples/encrypted_sentiment_analysis

**Comment by bcm-at-zama** [comment]
Could you help @jfrery ?

**Comment by jfrery** [comment]
Hi @I-E-E-E,

I suspect you are running with a glibc version that is not supported by our compiler.

Could you try this command and copy/paste the output here please?
```
ldd --version
```

We currently only support glibc>=2.28.

**Comment by bcm-at-zama** [comment]
Closing the issue
