### ISSUE TITLE
Unknown attributes: count_include_pad when compiling with compile_torch_model

### ISSUE THREAD

**Issue by NgesBrian** [zama-ai/concrete-ml#428]
## Summary
When develop a custom neural network and try to compile it using MNIST Dataset through compile_torch_model, I get an assertion error :
"AssertionError: Got the following unknown attributes: count_include_pad. Accepted attributes: ceil_mode, kernel_shape, pads, strides" 

I was expecting compilation and generation of the circuit which I will then use to train my model. 

- versions affected:
- python version: 3.10.12
- config : x86_64
- workaround (optional): remove the pooling layers but you are likely to run into other issues and above all, affect the accuracy of the network. 

Step by step procedure someone should follow to trigger the bug:

**Comment by RomanBredehoft** [comment]
Hello @NgesBrian ,
Indeed it seems that our AvgPool2D operator is missing support for the `count_include_pad` parameter. We are planning on fixing this in the near future and we will let you know when this is done 😉 

Thanks for the report !

**Comment by RomanBredehoft** [comment]
This is just to let you known that we have fixed the issue and it will be included in our upcoming release ! Besides, for now, we only support the `count_include_pad=1` behavior.
