### ISSUE TITLE
May I ask how to visualize the graph？

### ISSUE THREAD

**Issue by maxwellgodv** [zama-ai/concrete-ml#436]
I ran this [code](https://github.com/zama-ai/concrete-ml/blob/main/use_case_examples/cifar/cifar_brevitas_training/evaluate_one_example_fhe.py)`open("cifar10.graph", "w").write(str(quantized_numpy_module.fhe_circuit))
`. Executed this code sentence. And I have obtained the file cifar10.graph，how to visualize this file.

**Comment by andrei-stoian-zama** [comment]
It is not currently possible to visualize this graph, you can just analyze it in its text form. We will add this feature soon.
