### ISSUE TITLE
Quantized Unfold

### ISSUE THREAD

**Issue by tguerand** [zama-ai/concrete-ml#467]
## Feature request
An implementation of the `torch.nn.Unfold` in a quantized way. 
## Motivation

The unfold operation requested is not done here with the torch._C.im2col but with the fhe_conv function to have lower compilation times with concrete-python afterwards.
Doing an unfold with for loops / indexing is very slow compilation wise as it generates a huge MLIR compared to a simple convolution with kernels of a single 1 and zeros

**Comment by RomanBredehoft** [comment]
Indeed, that could be nice to support in Concrete ML !
