### ISSUE TITLE
Enhance the documentation for encrypted training

### ISSUE THREAD

**Issue by stoney95** [zama-ai/concrete-ml#502]
## Feature request

Disclaimer: I am very new to concrete-ml and FHE in general.

I am referring to the existing [example for encrypted training](https://github.com/zama-ai/concrete-ml/blob/release/1.4.x/docs/advanced_examples/LogisticRegressionTraining.ipynb). From my understanding the example works entirely on plaintext data. Or at least I would expect that the data is encrypted before it is fed into `model.fit`. In case I misunderstand the example I would be happy if you can clarify it for me. In case my understanding is correct, could you enhance the example to showcase the full workflow. 

## Motivation

I am very new to concrete ml and it is hard to understand when data is encrypted in the provided example for [Encrypted training](https://github.com/zama-ai/concrete-ml/blob/release/1.4.x/docs/advanced_examples/LogisticRegressionTraining.ipynb).

**Comment by andrei-stoian-zama** [comment]
Concrete ML implements training on encrypted data using the `fit` function, when specifying the `fhe="execute"` flag. In the demo you link the line is:

```
sgd_clf_binary_fhe.fit(X_binary, y_binary, fhe="execute") 
```

It is further explained in the documentation here: https://docs.zama.ai/concrete-ml/built-in-models/training

**Comment by fd0r** [comment]
To add some details to what @andrei-stoian-zama mentioned, there is no API at the moment to do something like `encrypt(data) -> train -> decrypt(weights)` in different steps, everything is merged in the `fit` function. You could craft one yourself by looking at what is implemented in the `fit` function but not be straightforward.

We'll add client-server support for encrypted training in a new release but you can already test with the `fit` method to see what kind of results of you can expect from encrypted training and with what runtime.

**Comment by stoney95** [comment]
@andrei-stoian-zama, @fd0r, thanks for your explanations and insights. The workflow `encrypt(data) -> train -> decrypt(weights)` is exactly what I was looking for. So, I will look forward to the release providing client-server support for encrypted training. @fd0r, is the release of that feature something you want to do "some time in the future" or is there already a plan when this will be available?

**Comment by jfrery** [comment]
Hi @stoney95,

You can find the full client-server pipeline process in the following GitHub Gist:

https://gist.github.com/jfrery/45c15cee8a073341b9a36606c954067f

This code already allows you to deploy the encrypted training. If you prefer the easier version using the concrete-ml API, that integration is underway, but it will be available soon.

Please don't hesitate to let me know if anything is unclear!

**Comment by KatsarosEf** [comment]
Hi @jfrery,

Thank you for the script! I am a bit confused, is the comment in line 87 correct? Should the server not just deserialize and serialize back after the computations? In my understanding, the server should not have access to the decrypted data. If the server does actually decrypt and re-encrypt the data, does it happen within server.run()?

Thanks in advance :)

**Comment by fd0r** [comment]
Hello @KatsarosEf , this is indeed a typo, nothing is decrypted, it's just serialization and desarialization 🙂

**Comment by jfrery** [comment]
I am closing this issue as I believe you were able to move on to your next step. Don't hesitate to open other issues if you encounter anything unclear.
