### ISSUE TITLE
Is there a way for the model to return the encrypted test set after performing the inference?

### ISSUE THREAD

**Issue by ReTire9** [zama-ai/concrete-ml#525]
Thank you very much for the project. I would like to ask how i can get the encrypted test set after performing the inference in FHE.

**Comment by RomanBredehoft** [comment]
Hello @ReTire9,
Could you explain a bit more what you are trying to achieve here, and more specifically why you would need the test set to be encrypted ?

In the mean time, I invite you to have a look at [our documentation](https://docs.zama.ai/concrete-ml/) where you might find answers to some of your questions. !
