### ISSUE TITLE
After model.compile, does the model exist in plaintext form or in ciphertext?

### ISSUE THREAD

**Issue by qxzhou1010** [zama-ai/concrete-ml#546]
After model.compile, does the model exist in plaintext form or in ciphertext?

Or in other words, does the inference under encryption involve **ciphertext data + plaintext model**? Or is it **ciphertext data + ciphertext model**?

**Comment by fd0r** [comment]
Hello @qxzhou1010 , at the moment in Concrete ML the model is in the clear, meaning that anyone that has access to the serialized circuit should be able to understand what the circuit computes.

Concrete ML is focused, for now, on encrypted data + clear model.

Doing the inference with an encrypted model would add quite a lot of complexity.

**Comment by qxzhou1010** [comment]
Thank you for your reply; I no longer have any issues on this point.
