### ISSUE TITLE
Faster TFHE Bootstrapping with Block Binary Keys

### ISSUE THREAD

**Issue by gogo9th** [zama-ai/concrete-ml#548]
## Feature request

I wonder if this paper's technique has been applied to concrete-ml: 

[Faster TFHE Bootstrapping with Block Binary Keys](https://eprint.iacr.org/2023/958)

## Motivation

The paper reports that this technique can reduce the bootstrapping time by almost half. 

p.s I have a small question. For pure TFHE tasks (without ML), does Zama provide a way to boost the speed by using GPU? Or does Zama use GPU used only for ML inferences/training?

**Comment by andrei-stoian-zama** [comment]
Hi! 

We're not using the method described in that paper in Concrete ML. 

I think tfhe-rs runs on GPUs, but you would get a more accurate answer on the https://github.com/zama-ai/tfhe-rs github or on our forums: https://community.zama.ai/c/tfhe-rs/13

Concrete ML does not currently use the GPU acceleration but we're working on it.
