### ISSUE TITLE
Comparison over encrypted integers

### ISSUE THREAD

**Issue by bhuvneshchaturvedi2512** [zama-ai/concrete-ml#555]
Could somebody please tell me whether it is possible to perform comparisons over two encrypted integers directly? I know one way is to convert the ciphertexts encrypting an integer into a set of ciphertexts encrypting each bit of the said integer and then use boolean operations, but I guess that would incur a severe overhead provided it is possible at all.

I am well aware that performing data-dependent branching in FHE over the server is a big no-no, since a semi-honest server may infer some secret information based on the path taken by the branching. However, the use case I am planning to implement requires this feature.

Any help will be appreciated.

**Comment by jfrery** [comment]
Hi @bhuvneshchaturvedi2512,

We do have a ways to compare two encrypted integers directly. You can check this page in the concrete-python documentation.

https://docs.zama.ai/concrete/tutorials/comparisons

**Comment by bhuvneshchaturvedi2512** [comment]
Hi @jfrery, thank you for your prompt response, and I'm sorry for responding this late. I checked some of the documentation's basic operations, and they are working as expected.

I am closing this issue from my side.

**Comment by bhuvneshchaturvedi2512** [comment]
I got the solution that I was looking for.
