### ISSUE TITLE
RuntimeError: Can't compile: Cannot find crypto parameters

### ISSUE THREAD

**Issue by bpradeep508** [zama-ai/concrete-ml#604]
n_bits = 6

q_module = compile_torch_model(model, X_train, rounding_threshold_bits=6, p_error=0.1)

start_time = time.time()
accs = test_with_concrete(
    q_module,
    test_dataloader,
    use_sim=True,
)
sim_time = time.time() - start_time

print(f"Simulated FHE execution for {n_bits} bit network accuracy: {accs:.2f}%")

error from second line. here X_train is not a mnist dataset given in example, custom dataset

**Comment by jfrery** [comment]
Hi @bpradeep508,

Looks like this is the code from the [CNN example](https://github.com/zama-ai/concrete-ml/blob/main/docs/advanced_examples/ConvolutionalNeuralNetwork.ipynb). Have you changed the data or model in the example?

Higher p_error, or a adding the `n_bits = 6` might help. But to understand why you see this error precisely we would need the architecture of your model.
