### ISSUE TITLE
[Question] How exactly the HybridFHE functions

### ISSUE THREAD

**Issue by matbee-eth** [zama-ai/concrete-ml#655]
If I understand correctly, the given example Phi1.5, we have to fine-tune the model with our custom data to get the benefits of an encrypted model input and output? Or is it replacing a certain part of the model, by inserting in a new python class, to need a private key to decode the data with a clients given public key?

Basically- Do we pretrain the model THEN implement hybrid, or do we implement hybrid THEN pretrain/finetune the model?

Or, putting it simply, just stripping a certain layer from the model and putting a key validation process in front of it?

**Comment by fd0r** [comment]
Hello @matbee-eth, what the hybrid model implements is the ability to delegate parts of the computation of a model to a FHE server.

I'm guessing you have a correct understanding with
>  stripping a certain layer from the model and putting a key validation process in front of it

but it's not just a key-validation process, the server itself cannot see the inputs nor the outputs of the computation thanks to FHE.
