### ISSUE TITLE
[Question] Discord link in explanation

### ISSUE THREAD

**Issue by sukrucildirr** [zama-ai/concrete-ml#672]
I didn't get. Why there is no discord link in explanation of discord? As i see everywhere, if you see explanation of discord, you can click it and go it. Maybe your discord link will change in future? You didn't add due to that?

https://github.com/zama-ai/concrete-ml/pull/668

**Comment by andrei-stoian-zama** [comment]
Thanks for the suggestion, it points out that the contact links on that page need an upgrade, but we actually want to link to another page which we'll do later on.

**Comment by sukrucildirr** [comment]
As I think, there will be site for Zama and there will be its own discord. I understand. Thanks.
