### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by thorntonmk** [zama-ai/concrete-ml#681]
## Summary

I have tested mutliple exampe codes like cifar 10, cifar 100. As previously reported, it takes lot of time on inference. Almost 25 ton30 min on inference. I have upgraded my hardware resources and did not notice a significant improvement in inference time. 
Can you please share some neural network code which is optimized for concerete ml and takes less time. Its okay if it works on image or text dataset.

**Comment by andrei-stoian-zama** [comment]
With the latest Concrete ML 1.5 running on a hpc7 192-core machine, the CIFAR use -case example should take around 40 seconds.
