### ISSUE TITLE
Hugging Face build error

### ISSUE THREAD

**Issue by matthiasgeihs** [zama-ai/concrete-ml#69]
Hey, just wanted to note that https://huggingface.co/spaces/zama-fhe/encrypted_sentiment_analysis is displaying a build error.

**Comment by fd0r** [comment]
We re-launched the build. It's working again: https://huggingface.co/spaces/zama-fhe/encrypted_sentiment_analysis 

Thanks again for letting us know 🙏🏼 , and don't hesitate to reach out on [discord](https://discord.com/channels/901152454077452399/1083021638544670720) if you have any questions regarding Concrete ML 😄
