### ISSUE TITLE
ONNX Gather operator missing

### ISSUE THREAD

**Issue by kc1212** [zama-ai/concrete-ml#7]
I'm following the the decision tree tutorial https://docs.zama.ai/concrete-ml/stable/user/advanced_examples/DecisionTreeClassifier.html but I'm changing the dataset to another one, e.g., https://www.openml.org/search?type=data&status=active&tags.tag=uci&qualities.NumberOfClasses=%3D_2&id=1480

But I'm getting the following error
```
ValueError: The following ONNX operators are required to convert the torch model to numpy but are not currently implemented: Gather.
Available ONNX operators: Abs, Acos, Acosh, Add, Asin, Asinh, Atan, Atanh, Celu, Clip, Constant, Conv, Cos, Cosh, Div, Elu, Equal, Erf, Exp, Gemm, Greater, HardSigmoid, Identity, LeakyRelu, Less, Log, MatMul, Mul, Not, Relu, Reshape, Selu, Sigmoid, Sin, Sinh, Softplus, Sub, Tan, Tanh, ThresholdedRelu
```
when running `.fit` or `.fit_benchmark` on the model.

I imagine this operator https://github.com/onnx/onnx/blob/main/docs/Changelog.md#gather-1 is not yet implemented.

**Comment by kc1212** [comment]
Maybe this function is needed https://github.com/onnx/onnx/blob/35092895d9bf3592e58f4710d098f8131afef259/onnx/backend/test/case/node/gatherelements.py#L11

**Comment by jfrery** [comment]
Hi @kc1212,

Thanks for the feedback ! The Gather operator is not yet implemented on our end as it is not necessary for now. This Gather node appears when classes do not start from 0 (e.g. `numpy.unique(y) = [1, 2, 3]`). We will fix this behavior in a later release. 

For now you can simply make sure that your labels start from 0 and the notebook should run (it will replace the Gather node by an ArgMax node which we support in the post processing step).

Let us know if that fixes your issue!

**Comment by kc1212** [comment]
Thanks for the quick response, the workaround fixes the issue.
