### ISSUE TITLE
When I run the fhe_compatibility, the program is killed

### ISSUE THREAD

**Issue by maxwellgodv** [zama-ai/concrete-ml#82]
qmodel = fhe_compatibility(quant_vgg, data)

print(
    f"With {param_c10['dataset_name']}, the circuit has a maximum bit-width of "
    f"{qmodel.fhe_circuit.graph.maximum_integer_bit_width()}-bits."
)

<img width="192" alt="1686310285723" src="https://github.com/zama-ai/concrete-ml/assets/127387074/cf6b835c-cb9f-4508-8a2d-414338670a99">

**Comment by andrei-stoian-zama** [comment]
Most likely your are running out of memory. Compilation may require large amounts of memory and you can check that for example with the `htop` tool or your System Monitor program. Check if you see a rising amount of memory being used quickly going to 100% and then a crash. How much RAM do you have on your machine ?

**Comment by maxwellgodv** [comment]
> 

16

**Comment by maxwellgodv** [comment]
> 
How much RAM do I need？

**Comment by maxwellgodv** [comment]
> 16GB might not be enough for CIFAR, but the test I suggested in my previous reply should help you determine if you're running into memory issues

yes, it is memory issues.If I use the image size of 3 * 224 * 224, how much RAM would I need？

**Comment by maxwellgodv** [comment]
> It's hard to say and depends on multiple factors. Mainly the complexity of your model and the size of the dataset that you use to compile your model.

If I use the image size of 3 * 224 * 224, how much RAM would I need？

**Comment by andrei-stoian-zama** [comment]
That image size might require much more than 16GB, I think you may get away with 32GB for an image oe 3x32x32.
