### ISSUE TITLE
No module named 'concrete.fhe'?

### ISSUE THREAD

**Issue by maxwellgodv** [zama-ai/concrete-ml#83]
![image](https://github.com/zama-ai/concrete-ml/assets/127387074/96c1e045-764b-49d9-8a58-8c92bf6eeca8)

**Comment by fd0r** [comment]
Hello @maxwellgodv ,

Could you check that you have Concrete Python installed in your environment please ?

`python -m pip show concrete-python`

**Comment by maxwellgodv** [comment]
> python -m pip show concrete-python

I use pip install concrete-python to install , but the result as follow:
<img width="764" alt="image" src="https://github.com/zama-ai/concrete-ml/assets/127387074/1c4788ad-b64a-4bd2-8146-89e25261f606">

**Comment by fd0r** [comment]
Could you provide a bit more context on the system that you are using please ?

Mainly the OS and CPU architecture

**Comment by maxwellgodv** [comment]
> 您能否提供有关您正在使用的系统的更多信息？
> 
> 主要是您运行的操作系统，CPU架构和python版本

![image](https://github.com/zama-ai/concrete-ml/assets/127387074/729de7d6-36ce-46ff-af80-372936682ae3)
Are these ？

**Comment by fd0r** [comment]
Alright it seems like you are running an old version of Ubuntu.
Could you put the output of `ldd --version` here?
Concrete Python has a `glibc` version requirement that may not be satisfied by your current setup.

**Comment by maxwellgodv** [comment]
![image](https://github.com/zama-ai/concrete-ml/assets/127387074/1db4280f-efe1-48c2-990a-2e39cab723d7)

Is this it？How can i upgrade it?

**Comment by fd0r** [comment]
I believe that's it indeed.
Concrete Python requires Glibc version to be 2.28 or above.
I never had to update it myself but a quick search showed me this links:
- https://askubuntu.com/questions/736208/upgrading-glibc
- https://stackoverflow.com/questions/72513993/how-to-install-glibc-2-29-or-higher-in-ubuntu-18-04

**Comment by maxwellgodv** [comment]
ok ,thank you very much
