### ISSUE TITLE
GPU acceleration in  concrete-ml ?

### ISSUE THREAD

**Issue by S1eepeng** [zama-ai/concrete-ml#831]
Hello, to the best of our knowledge, concrete-ml currently doesn't support GPU acceleration in `q_module.forward().` We found that most fhe-ml libraries doesn't support GPU yet. Could you explain what is the main difficulty in supporting GPU acceleration in fhe-ml?Or are there any fhe-ml libraries that supports GPU acceleration?
Thank you a lot for your reply,we will greatly appreciate it!

**Comment by bcm-at-zama** [comment]
Hello. Concrete was delivered in Q2 with a support for GPU. Next quarter, Concrete ML will have this support. It's not a particular difficulty, it's just a matter of patience. Cheers

**Comment by S1eepeng** [comment]
Thanks for your reply,cheers!

**Comment by bcm-at-zama** [comment]
Stay tuned with our Zama releases! eg, in https://www.zama.ai/blog
