### ISSUE TITLE
such an error on the Mac computer

### ISSUE THREAD

**Issue by maxwellgodv** [zama-ai/concrete-ml#84]
<img width="1593" alt="image" src="https://github.com/zama-ai/concrete-ml/assets/127387074/25b3a90d-3404-43c4-b87f-e84e6879b7ef">

**Comment by fd0r** [comment]
Hello @maxwellgodv , your error seams to come from pytorch, could you please provide a way to replicate your issue?

**Comment by maxwellgodv** [comment]
/Users/macbookpro/opt/anaconda3/envs/pytorch1/lib/python3.8/multiprocessing/resource tracker.p: 216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
warnings.warn('resource_tracker: There appear to be %d'

**Comment by bcm-at-zama** [comment]
Generally speaking: _warnings_ are often not errors.
