### ISSUE TITLE
Could not initialize NNPACK! Reason: Unsupported hardware.

### ISSUE THREAD

**Issue by nazarpysko** [zama-ai/concrete-ml#869]
I was trying to experiment with FHE CNNs in a server via SSH by running this [notebook](https://github.com/zama-ai/concrete-ml/blob/main/docs/advanced_examples/ConvolutionalNeuralNetwork.ipynb) from one of your tutorials. 

I expected to run it without major changes but unfortunately I get Kernel crashes when trying to run the cell from `Test the network using Simulation` section. More specifically, it seems that the problematic part is the `compile_torch_model` function. It seems that this is because `avx2` instruction is missing from my CPU's instruction set. 

``` bash
lscpu | grep avx2
```
The previous command does not return nothing. Also, as suggested in some random forums, I tried to add the follwing line right after the torch import but I get an error.

``` python
import torch 
torch.backends.nnpack.enabled = False
```

``` python
AttributeError                            Traceback (most recent call last)
Cell In[2], [line 5](vscode-notebook-cell:?execution_count=2&line=5)
      [3](vscode-notebook-cell:?execution_count=2&line=3) import numpy as np
      [4](vscode-notebook-cell:?execution_count=2&line=4) import torch
----> [5](vscode-notebook-cell:?execution_count=2&line=5) torch.backends.nnpack.enabled = False
      [7](vscode-notebook-cell:?execution_count=2&line=7) import torch.utils
      [8](vscode-notebook-cell:?execution_count=2&line=8) from sklearn.datasets import load_digits

AttributeError: module 'torch.backends' has no attribute 'nnpack'
``` 
I can run it in other machine but I was wondering if there is some workaround. Should I keep trying running in this machine or should I move to another one? 

## Machine & Software used:
- CPU: Intel(R) Xeon(R) CPU E5520 @ 2.27GHz
- OS: Ubuntu 20.04.6 LTS
- Python: 3.8.19
- concrete-ml: 1.6.1

**Comment by bcm-at-zama** [comment]
Hello

If I am not wrong, your processor is https://www.intel.com/content/www/us/en/products/sku/40200/intel-xeon-processor-e5520-8m-cache-2-26-ghz-5-86-gts-intel-qpi/specifications.html?

Then, it's said that it was launched Q1 2009 and that it's End of Servicing Lifetime. Sorry, Concrete and Concrete ML need more recent CPUs. 

Could you try finding a more recent computer? It will also make your execution time much better.

**Comment by nazarpysko** [comment]
Yes, that was the CPU I was talking about. I know this is an old version and a newer one should be used. I just was wondering if it was possible to run concrete-ml on older CPUs like this. Thanks for the quick response.

**Comment by bcm-at-zama** [comment]
With some work, it might be doable to use older CPU but it's often not worth it. Plus here, the issue you seem to have is with Torch, which is actually not made by Zama but by Meta. i guess they have deprecated this old HW as well.
