### ISSUE TITLE
What determines how much RAM i need when I run a function ‘fhe_compatibility’

### ISSUE THREAD

**Issue by maxwellgodv** [zama-ai/concrete-ml#88]
<img width="554" alt="1686545392652" src="https://github.com/zama-ai/concrete-ml/assets/127387074/3691f829-c823-4c34-be0a-2cb13846ae9f">

**Comment by fd0r** [comment]
Hello @maxwellgodv, 
What you mean is that the programs get killed on your machine in its current state?

**Comment by fd0r** [comment]
The answer to the RAM question is the same as https://github.com/zama-ai/concrete-ml/issues/82#issuecomment-1586745201 .
Basically it depends.

Could you please contain your questions to a single issue, as it is easier for us track please? 😄

**Comment by RomanBredehoft** [comment]
Let's close this issue and continue our discussion in the other one !
