### ISSUE TITLE
How to build a СNN on BFV?

### ISSUE THREAD

**Issue by reaneling** [zama-ai/concrete-ml#910]
Hello!
I am doing research related to neural networks and homomorphic encryption. Your library is amazing and allows you to explore the TFHE scheme! And as I understand it, the example of the convolutional neural network works with this scheme. However, a question arises, in one of the Issue I saw that you have support for several homomorphic encryption schemes, including the BFV scheme. Therefore, I have a question, how to build a CNN with this scheme?
If I am wrong and the CNN already works on BFV, is it possible to build it on TFHE?

P.S. (This is about an example docs/advanced_examples/ConvolutionalNeuralNetwork.ipynb)

**Comment by jfrery** [comment]
Hello! Concrete ML is based on the TFHE scheme, we don't support other schemes.

The notebook you are linking will make the CNN work within the TFHE scheme.

**Comment by reaneling** [comment]
Okey, thank you!
