### ISSUE TITLE
How much RAM do I need？

### ISSUE THREAD

**Issue by maxwellgodv** [zama-ai/concrete-ml#92]
<img width="1132" alt="1687417317985(1)" src="https://github.com/zama-ai/concrete-ml/assets/127387074/b37bfe75-f302-4cbb-8883-55e6625a3714">
I can successfully run cifar100, but I cannot run cifar10，
  now I have 128G RAM

**Comment by RomanBredehoft** [comment]
Hello ! Awesome that you've been able to run Cifar100. Could you give us the error message you get when trying to run Cifar10 ? 

Many thanks !

**Comment by RomanBredehoft** [comment]
Actually closing this issue as I believe you made your problem more explicit in this one : https://github.com/zama-ai/concrete-ml/issues/93
