### ISSUE TITLE
When using the cifar-10 data set, the program is killed when it runs to the fhe_compatibility function

### ISSUE THREAD

**Issue by maxwellgodv** [zama-ai/concrete-ml#93]
When I run the example of cifar_brevitas_finetiuning, cifar-100 can run normally, but once cifar-10 runs to the fhe_compatibility function, the program is killed, and my memory is 128G
![image](https://github.com/zama-ai/concrete-ml/assets/127387074/aca20b2e-f6fa-4078-ab7a-7ef3b1a91352)
Here is my memory usage for running the program for the dataset using cifar-10
![image](https://github.com/zama-ai/concrete-ml/assets/127387074/de505572-d4bf-4123-94fc-49a62a5f69a3)

**Comment by maxwellgodv** [comment]
<img width="656" alt="1687768980430" src="https://github.com/zama-ai/concrete-ml/assets/127387074/13b2d94c-a8d4-4e0d-be28-56f98e621f78">

**Comment by RomanBredehoft** [comment]
Hello, 
We are currently looking into your issue and will get back to you as soon as we know more about it !

**Comment by kcelia** [comment]
Hi @maxwellgodv, 

We released a new version of Concrete ML recently, could you please test on the latest version and let us know if you still encounter this issue ?

Thanks!

**Comment by maxwellgodv** [comment]
> Hi @maxwellgodv,
> 
> We released a new version of Concrete ML recently, could you please test on the latest version and let us know if you still encounter this issue ?
> 
> Thanks!

Ok , can i use the commad “pip install concrete-ml“ to get new version?

**Comment by maxwellgodv** [comment]
Thank you. The problem has been resolved。

**Comment by RomanBredehoft** [comment]
Closing the issue as updating Concrete ML's version seems to have solved it
