### ISSUE TITLE
predict() got an unexpected keyword argument 'fhe'

### ISSUE THREAD

**Issue by bhuvneshchaturvedi2512** [zama-ai/concrete-ml#98]
I am trying to run the logistic regression example provided in "A simple Concrete ML example with scikit-learn" on the concrete ml GitHub page.

However, while running the code, I am getting the following error:

predict() got an unexpected keyword argument 'fhe'

while executing the following statement:

y_pred_fhe = model.predict(X_test, fhe="execute")

I don't know why this is happening. I am running the code on Ubuntu 20.04 LTS. I have installed concrete ml through the "pip" method in Python 3.8.10

I am also receiving the following warning:

PkgResourcesDeprecationWarning: 0.23ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(

**Comment by andrei-stoian-zama** [comment]
Can you please link us the example you are running ?

It would seem to me that you are not using the latest Concrete ML version. Can you please post the output of this command?

```
pip freeze | grep concrete
```

**Comment by bhuvneshchaturvedi2512** [comment]
Hi @andrei-stoian-zama, I have fixed this issue on my own. Apparently, the library was not installed properly when done through "pip install concrete-ml" command. Maybe a problem with the precompiled version.

I unistalled the library and reinstalled it using "pip3 install git+https://github.com/zama-ai/concrete-ml.git"

I hope this helps someone in the future.

**Comment by andrei-stoian-zama** [comment]
Great! thanks for the update! If you still want to go with the normal install, for Ubuntu 20 you might need to update setuptools to properly install concrete-ml through pip:

```
pip install -U pip wheel setuptools
pip install concrete-ml
```
